name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Or your primary branch name

env:
  PROJECT_ID: optimum-tea-458606-m2
  SERVICE_NAME: wavesend
  REGION: us-central1
  REGISTRY: us-central1-docker.pkg.dev/optimum-tea-458606-m2/wavesend-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Configure Docker to use gcloud credentials
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        docker tag ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:latest
        
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        traffic: 100
        env_vars: |
          SPRING_PROFILES_ACTIVE=prod